var data=[
  {
    "number": 1,
    "Goal": "Improve awareness of code development and code adoption.",
    "Strategy Name": "Advertising Campaign for Development and Code Adoption by Providing DOB NOW Build Support, Expand Plan Exam QA/QC Process and Utilizing DBCs, CPEs, ACPEs, C&Zs, & PE Staff",
    "Summary/ Objective": "The reason for the project is to broadcast the code development and adoption process to make industry, professionals, and DOB staff aware of upcoming changes to code provisions through specific publications and to improve compliance.\nIt is necessary to communicate upcoming changes to industry, professionals, and DOB staff.  Informative forms of communication are necessary so that everyone is made aware of changes thereby making processes at the DOB more efficient and transparent.  Additional guidance materials to the public will also improve compliance.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "50%"
  },
  {
    "number": 2,
    "Goal": "Improve awareness of code development and code adoption.",
    "Strategy Name": "Advertising Campaign for Development and Code Adoption by Leveraging Data and Metrics",
    "Summary/ Objective": "The reason for the project is to broadcast the code development and adoption process to make industry, professionals, and DOB staff aware of upcoming changes to code provisions and operations.\nThe public should be given information to be aware of changes to the code and operations to have a smoother transition.  The analysis of data as it relates to code development and adoption can provide an objective ruler from which to measure past processes and efficiency compared with upcoming, predicted processes and efficiency that are a result of changes to code.    DOB and the public will benefit from learning how updates to the code impact applications.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "60%"
  },
  {
    "number": 3,
    "Goal": "Support code development and adoption in order to maintain the safety and welfare of the public in New York City.",
    "Strategy Name": "Continue to Support Code Development and Adoption",
    "Summary/ Objective": "Code development and adoption is currently under way and in varying stages of completion for a number of code types.  The development and eventual adoption must be supported in order to ensure that the effort is communicated and delivered properly to end users (industry, homeowners, public) and those who must enforce and interpret it (DOB staff).  \nCodes must be updated and issued every certain number of years in accordance with city, state, and federal guidelines.  The process involves close coordination with industry, public, and DOB staff.  The effort must be supported in order to meet deadlines and ultimately keep the public safe.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 4,
    "Goal": "Support code development and adoption in order to maintain the safety and welfare of the public in New York City.",
    "Strategy Name": "Continue to Support Code Development and Adoption through Reorganization",
    "Summary/ Objective": "Code development and adoption is currently under way and in varying stages of completion for a number of code types.  The development and eventual adoption must be supported in order to ensure that the effort is communicated and delivered properly to end users (industry, homeowners, public) and those who must enforce and interpret it (DOB staff).  \n\nCodes must be updated and issued every certain number of years in accordance with city, state, and federal guidelines.  The process involves close coordination with industry, public, and DOB staff.  The effort must be supported in order to meet deadlines and ultimately keep the public safe.  The reorganization and reallocation of DOB staff will ensure that the best resources are being used in the best way to achieve results.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 5,
    "Goal": "Create process for DOB staff to make the plan examination process consistent and efficient among several application types.",
    "Strategy Name": "Process and Centralize Hub Process and Centralize Disparate Plan Review Functions using DOB NOW Build Team Structure",
    "Summary/ Objective": "Currently the DOB NOW Build interface only supports certain functions and applications.  The industry would benefit from one source of interacting with the DOB online rather than several different interfaces.  This would also be beneficial to DOB staff.  \n\nCurrently there are several locations to go to online (BIS, DOB NOW, etc.).  By maintaining one source of all projects, the industry can go to one place for all their needs.  The DOB staff group that handles each project type must now be reorganized in order to accommodate the shift from not being handled on the DOB NOW Build platform to being handled on the DOB NOW Build platform.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 6,
    "Goal": "Improvements include the following items:  Property Profile information which normally resides in BIS will move to DOB NOW Build.  The certificate of occupancy will be a part of the new property profile in DOB NOW Build.\nIn-person DOB staff procedures to support the technological interface include the following items.  The setup of physical kiosks in each borough office will provide additional support.",
    "Strategy Name": "Support and Guide DOB NOW Build Development",
    "Summary/ Objective": "The reason for the project is to continue improving the DOB NOW Build process to make it a more efficient and effective tool for the public and the DOB.\n\nThe DOB NOW Build portal is still developing and should include improvements based on comments from DOB staff and industry.  Improvements must be made to the technological interface and the in-person DOB staff procedures that support that interface.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 7,
    "Goal": "The advertising campaign of DOB NOW Build will increase usage of the system and allow industry to acknowledge the steps being taken by DOB to constantly improve the system.",
    "Strategy Name": "Support and Guide DOB NOW Build Development through Advertising Campaign and Code Adoption",
    "Summary/ Objective": "The DOB NOW Build process is relatively new to the industry, and improvements to the system and metrics should be highlighted for their use and benefit.\n\nAs the industry is more aware of improvements to the DOB NOW Build system, they would increase their usage of the system and acknowledge that the DOB is making an effort to make the system better based on their comments.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 8,
    "Goal": "The goal is to increase the speed at which the certificate of occupancy is processed by DOB staff for use by the industry.",
    "Strategy Name": "Support and Guide DOB NOW Build Development by Simplifying, Accerlating, and Publishing the Certificate of Occupancy Process",
    "Summary/ Objective": "The certificate of occupancy approval process can be lengthy and may no longer effectively address current real estate environment.  DOB staff would benefit from a more streamlined process that allows them to easily process the C of O.  Currently, the C of O is not a part of the DOB NOW Build interface.  Making the process a part of the DOB NOW interface will help speed up the overall process for industry and DOB staff.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 9,
    "Goal": "The goal is to be able to communicate the project information to the DOB staff coherently on the occasions when the DOB NOW Build interface does not sufficiently communicate hat info.",
    "Strategy Name": "Support and Guide DOB NOW Build Development by Providing Targeted Customer Service Training for Plan Examiners",
    "Summary/ Objective": "While the technological interface of DOB NOW Build is integral to its usage, the in-person contact with DOB staff is also an important way to process information and applications.\n\nThere may be some more complex applications which are not easily understood through drawings alone.  Other applications may present drawings that are not legible no matter what the complexity.  Also, there may be DOB NOW Build users who are not technologically savvy who would benefit from discussing their project in person.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 10,
    "Goal": "Cross training DOB staff to make the plan examination process consistent and efficient among several application types among certain required documents. This will be achieved by rotating staff through various teams based on a developed workload management system.",
    "Strategy Name": "Support and Guide DOB NOW Build Development by Expanding Plan Exam QC-QA Process:  Institute DOB NOW Build team structure per Team Structure presentation",
    "Summary/ Objective": "Each plan examiner becomes experienced in different types of projects and ways of examining each plan.  Some plan examiners may have more work than others.  Some plan examiners may have efficient methods of plan examining that they can share with others.\n\nOne plan examiner may be assigned too much work in an area that he or she is unfamiliar with whereas another may be assigned little work in an area that he or she is familiar with.  This affects the plan examiner and indirectly affects the industry who either benefits or is negatively affected by the workload distribution and skill of the examiner.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 11,
    "Goal": "Create streamlined guidelines for DOB staff to make the plan examination process consistent and efficient among several application types among certain required documents. Provide support for plan examiners through regular training for consistency and create new processes to work in DOB NOW to resolve objections with ACPEs.",
    "Strategy Name": "Support and Guide DOB NOW Build Development by Expanding Plan Exam QC-QA Process:  Utliize DBCs, CPEs, ACPEs, C&Zs & PE staff",
    "Summary/ Objective": "The plan examination process can be frustrating to the industry at times.  The process differs from one plan examiner to another because there are little to no cohesive guidelines to guide the examiner in his or her review of an application.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 12,
    "Goal": "Use data and metric tools to analyse service levels with the goal of improving them.",
    "Strategy Name": "Leverage Data & Metrics",
    "Summary/ Objective": "Data is powerful tool for tracking progress and quantifying improvements based on objective analysis.  By reviewing data, one can better understand past patterns of work flow and predict future patterns.\n\nBy using data analysis to track the number of days it takes for a review of an application to reach review status, DOB staff can identify which processes take the greatest amount of time and highlight areas where efficiency can be improved.  New tools to measure this data can be developed and tailored to meet needs.  Discussion with borough commissioners will also provide insight into the reasons certain numbers are higher or lower.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 13,
    "Goal": "Improve QA/QC process for development inspections.",
    "Strategy Name": "Revise QA & QC Process for Development Inspections",
    "Summary/ Objective": "Based on comments from industry, professionals, and DOB staff, the quality assurance and quality control aspects of Development Inspections would benefit from improvement. \n\nDiscussion with DOB staff indicates that there is room for improvement in the QA/QC process and further discussion is required to develop updated protocols and a better understanding of actions to be taken to improve the process.",
    "Source": "NYC Department of Buildings Development Bureau 2020 Powerpoint presentation",
    "Bureau": "Development and Technical Affairs",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 14,
    "Goal": "Innovation",
    "Strategy Name": "Sustainability Design Competition",
    "Summary/ Objective": "Carbon Neutrality Innovation Challenge - the agency’s first-ever competition for ideas to increase energy efficiency among large buildings, which are the city’s #1 source of greenhouse gas emissions.",
    "Source": "",
    "Bureau": "First Commissioners Office",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 15,
    "Goal": "Innovation",
    "Strategy Name": "Building Innovation Competition",
    "Summary/ Objective": "Building Code Innovation Challenge - the agency's first-ever competition for ideas from the real estate and construction industries, as well as the general public, on practical steps the city can take to modernize the construction process and improve the safety of buildings and workers.",
    "Source": "",
    "Bureau": "First Commissioners Office",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 16,
    "Goal": "Innovation",
    "Strategy Name": "DOB Innovation Committee",
    "Summary/ Objective": "A forward-looking internal DOB committee to look at new technology advancements in construction process and how DOB can utilize them.\nLed by Tech Affairs, will include IT, Analytics, Enforcement, Development to do research and help steer the discussion.\nThis committee will encourage grassroots DOB projects which highlight Commissioner La Rocca’s areas of innovation:\n(•) Customer service\n(•) Site safety\n(•) Tenant protection\n(•) Sustainability",
    "Source": "",
    "Bureau": "First Commissioners Office",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 17,
    "Goal": "Develop talent from within for specialty inspection units",
    "Strategy Name": "Personel",
    "Summary/ Objective": "Fill hard to recruit units such Elevators, Boilers, and Cranes & Derricks by training in-house, out of college students, using L1 inspectors lines.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 18,
    "Goal": "Identify measurables for staff productivity",
    "Strategy Name": "Personel",
    "Summary/ Objective": "Enforcement institutes mandate for all unit employees get annual reviews.  This was implemented in 2018.",
    "Source": "Bureau Goals",
    "Bureau": "",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 19,
    "Goal": "Institute 2nd shift system for all Inspection Units",
    "Strategy Name": "Personel",
    "Summary/ Objective": "The will give the Agency to be more responsive to off-hours inspection request and reduce SLA on complaints.  This will reduce OT cost by 75%",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 20,
    "Goal": "Develop Field Training Officer Program",
    "Strategy Name": "Training and Continuing Education",
    "Summary/ Objective": "Obtain Inspector retention",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 21,
    "Goal": "Cross train inspection units",
    "Strategy Name": "Training and Continuing Education",
    "Summary/ Objective": "Well rounded Inspectors needed Institute One-Stop shop units. Remove the Silos between units by enforcing rotation program.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 22,
    "Goal": "Issue process flow postcards to building owners",
    "Strategy Name": "Customer Service",
    "Summary/ Objective": "Owners are simply unaware of the process for services or clearing violations; it allows for professionals and the industry to take advantage of that lack of knowledge.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 23,
    "Goal": "Issue Monthly Enforcement Newsletter",
    "Strategy Name": "Customer Service",
    "Summary/ Objective": "Transparency will be public on the performance of the industry with regard to construction safety.  Identify Top 10 violations citywide. This will reduce construction accidents",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 24,
    "Goal": "Reduce or remove loopholes and ambiguity in  Building code",
    "Strategy Name": "Customer Service",
    "Summary/ Objective": "Several units (Boilers, Elevators, C&D) have expressed a need to make changes to the code as the they encounter loopholes or areas that would improve public safety",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 25,
    "Goal": "Revamp inspectorial structure for equitable division of workload and improved efficiency",
    "Strategy Name": "Oprational Improvements",
    "Summary/ Objective": "The objective is to realign the workload among Chiefs and Asst. Chiefs to allow supervisors to focus more on field supervision and other high volume tasks.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 26,
    "Goal": "Revaluate service levels",
    "Strategy Name": "Oprational Improvements",
    "Summary/ Objective": "Canvas all unit for SLA targets.\nChange target to be more in line with actual production, public expectation, efficiency rates, and staff availability",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 27,
    "Goal": "Proactive enforcement on Vacates, SWOs, and IED/EDs",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 28,
    "Goal": "Develop a Major Buildings Unit",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "Dedicated Unit for large and complex projects citywide in a fee based program.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 29,
    "Goal": "Consolidate Engineering Units",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "Maximize knowledge based and reduce silos or duplication of efforts between the units. Increase production for investigations and audits",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 30,
    "Goal": "Modernize Audit capabilities using predictive analysis",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "Create a High Risk Construction Oversight group to review these building pre permit. Capture all borough plans exam blind spots. (e.g. Alt1, Alt2, Demo, Excavation, Etc.)",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 31,
    "Goal": "Enforcement bureau using same Information System",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "No longer will there be half the unit in DOBNOW or Mobile Summons and the rest in BIS and paper.  This reduces productivity and the ability to respond effectively",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 32,
    "Goal": "Operationalize the Building Census for Proactive Enforcement",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "Possible issues or problem areas are flagged for closer evaluation during pre-permit process.  During construction monitoring plans can be instituted to avoid issues.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  },
  {
    "number": 33,
    "Goal": "Remove or reduce use of Auto finalization",
    "Strategy Name": "Operational Improvements",
    "Summary/ Objective": "Remove the Autofinalize or Restrict the use of autofinalization to the lowest level disposition types.",
    "Source": "Bureau Goals",
    "Bureau": "Enforcement",
    "Start Date": "",
    "Projected Completion Date": "",
    "Status": "",
    "% Completion of Stategy": "0%"
  }
]
